name: CI Test

on:
  workflow_dispatch:

env:
  POETRY_VERSION: "1.8.3"
  POETRY_URL: https://install.python-poetry.org

jobs:
  linter_tester:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      # LLM_MODEL_NAME: ${{ secrets.LLM_MODEL_NAME }}
      # LLM_MODEL_API_KEY: ${{ secrets.LLM_MODEL_API_KEY }}
      AGENTS_LLM_CONFIG_JSON: ${{ secrets.AGENTS_LLM_CONFIG_JSON }}
      AGENTS_LLM_CONFIG_FILE_REF_KEY: ${{ vars.AGENTS_LLM_CONFIG_FILE_REF_KEY }}
      AGENTS_LLM_CONFIG_FILE: ${{ vars.AGENTS_LLM_CONFIG_FILE }}
      GEO_API_KEY: ${{ secrets.GEO_API_KEY }}
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python 
      ENABLE_TELEMETRY: 0
      AUTO_MODE: 1
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
        id: setup_python
      # Poetry cache depends on OS, Python version and Poetry version.
      - name: Cache Poetry cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}
      # virtualenv cache should depends on OS, Python version and `poetry.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install project
        run: make install-extra
      - name: Run linter
        run: make lint
      - name: Write AGENTS_LLM_CONFIG_JSON to file
        run: |
          ./helper_scripts/write_var_to_json.sh ${{ vars.AGENTS_LLM_CONFIG_FILE }}
      - name: Run tests
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          make test
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}