name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  UV_VERSION: "0.4.29"

jobs:
  linter_tester:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      LLM_MODEL_NAME: ${{ secrets.LLM_MODEL_NAME }}
      LLM_MODEL_API_KEY: ${{ secrets.LLM_MODEL_API_KEY }}
      GEO_API_KEY: ${{ secrets.GEO_API_KEY }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
        id: setup_python
      # UV cache depends on OS, Python version and UV version.
      - name: Cache UV cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.UV_VERSION }}
      # virtualenv cache should depends on OS, Python version and `uv.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: uv-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install UV ${{ env.UV_VERSION }}
        run: |
          pip install uv==${{ env.UV_VERSION }}
      - name: Install project
        run: make install-extra
      - name: Run linter
        run: make lint
      # - name: Run tests
      #   run: make test
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}