name: CI Non-Main

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]
  workflow_dispatch:
    inputs:
      LLM_MODEL_NAME:
        description: "LLM Model Name (required)"
        required: true
      LLM_MODEL_API_KEY:
        description: "LLM Model API Key (required)"
        required: true

env:
  UV_VERSION: "0.4.29"


jobs:
  linter_tester:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      LLM_MODEL_NAME: ${{ github.event.inputs.LLM_MODEL_NAME }}
      LLM_MODEL_API_KEY: ${{ github.event.inputs.LLM_MODEL_API_KEY }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
        id: setup_python
      # UV cache depends on OS, Python version and UV version.
      - name: Cache UV cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.UV_VERSION }}
      # virtualenv cache should depends on OS, Python version and `uv.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: uv-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install UV ${{ env.UV_VERSION }}
        run: |
          pip install uv==${{ env.UV_VERSION }}
      - name: Install project
        run: make install-extra
      - name: Run linter
        run: make lint
